openapi: 3.1.0
info:
  title: Nettspend API
  description: An API providing detailed information about the rapper Nettspend.
  version: 2.1.0
servers:
  - url: https://matix7z.github.io/Nettspend-GPT
    description: Production server
paths:
  /openai.yaml:
    get:
      operationId: getNettspendInfo
      summary: Retrieve information about Nettspend
      description: Returns comprehensive details about Nettspend, including his real name, background, music career, influences, and more.
      responses:
        "200":
          description: Detailed information about Nettspend
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NettspendResponse"
components:
  schemas:
    NettspendResponse:
      type: object
      properties:
        realName:
          type: string
          description: Nettspend's real name.
          example: Gunner Shepardson
        birthDate:
          type: string
          format: date
          description: Nettspend's date of birth.
          example: 2007-03-18
        origin:
          type: string
          description: Nettspend's place of origin.
          example: Richmond, Virginia
        influences:
          type: array
          items:
            type: string
          description: Artists who influenced Nettspend.
          example:
            - Chief Keef
            - Lil Uzi Vert
            - Young Thug
            - Michael Jackson
            - Katy Perry
            - Justin Bieber
        careerHighlights:
          type: object
          properties:
            viralMoment:
              type: string
              description: Nettspend's viral moment.
              example: A snippet of "Drankdrankdrank" went viral on Twitter in late 2023.
            debutMixtape:
              type: string
              description: Nettspend's debut mixtape.
              example: Bad Ass F*cking Kid
            collectives:
              type: array
              items:
                type: string
              description: Rap collectives Nettspend is associated with.
              example:
                - Novagang
                - 1c34
            collaborations:
              type: array
              items:
                type: string
              description: Artists Nettspend has collaborated with.
              example:
                - Xaviersobased
                - OsamaSon
            festivals:
              type: array
              items:
                type: string
              description: Festivals where Nettspend has performed.
              example:
                - Rolling Loud
        musicStyle:
          type: object
          properties:
            genres:
              type: array
              items:
                type: string
              description: Genres influencing Nettspend's music.
              example:
                - Trap
                - Jerk
            characteristics:
              type: string
              description: Description of Nettspend's sound.
              example: Distorted 808s, loose piano riffs, and shimmering synthesizers.
            mediaDescription:
              type: string
              description: Media description of Nettspend's music style.
              example: Post-post-rage
        notableTracks:
          type: array
          items:
            type: string
          description: Some of Nettspend's notable tracks.
          example:
            - Shine N Peace
            - We Not Like You
            - F*ck Swag
        impact:
          type: string
          description: Nettspend's significance in the music scene.
          example: Rising star in the hip-hop genre despite his young age.
        latestAchievements:
          type: object
          properties:
            awards:
              type: array
              items:
                type: string
              description: Awards and recognitions Nettspend has received.
              example:
                - Best New Artist 2024 (Rolling Loud Awards)
                - Viral Track of the Year 2023
            streamingStats:
              type: object
              properties:
                monthlyListeners:
                  type: integer
                  description: Monthly listeners on Spotify.
                  example: 500000
                totalStreams:
                  type: integer
                  description: Total streams across all platforms.
                  example: 20000000
        funFacts:
          type: array
          items:
            type: string
          description: Fun facts about Nettspend.
          example:
            - Started making music at the age of 15.
            - Loves anime and often references it in his music.
            - Known for his vibrant stage presence and energy.
        communityPerception:
          type: object
          properties:
            subredditFollowers:
              type: integer
              description: Number of followers on the Nettspend subreddit.
              example: 10000
            fanDiscussions:
              type: array
              items:
                type: string
              description: Popular topics discussed by fans.
              example:
                - Comparisons to Rei Ayanami from Neon Genesis Evangelion
                - Requests for instrumental sheets of his tracks
        controversies:
          type: array
          items:
            type: object
          description: Controversies involving Nettspend.
          example:
            - incident:
                type: string
                description: Description of the controversy.
                example: Alleged Instagram DMs with Rhonda Moore, leading to the "I got racks now Rhonda" meme.
              date:
                type: string
                format: date
                description: Date of the incident.
                example: 2024-10-24
              resolution:
                type: string
                description: Outcome or current status.
                example: Nettspend addressed the situation in interviews, denying the authenticity of the messages.
